import { useState } from 'react';
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useAudioPlayer, useAudioPlayerStatus } from 'expo-audio';
import { PaperBackground } from '../components/PaperBackground';
import { Screen } from '../components/Screen';
import { colors } from '../constants/theme';
import { useApp } from '../context/AppContext';
import { DiaryEntry } from '../types';
import { formatThaiDate } from '../utils/date';

type Filter = 'all' | 'checkin' | 'diary' | 'unsent';

export function HistoryScreen() {
  const { entries, diaryEntries, urgeEntries, deleteDiaryEntry, deleteUrgeEntry } = useApp();
  const [filter, setFilter] = useState<Filter>('all');
  const [selectedDiary, setSelectedDiary] = useState<DiaryEntry | null>(null);
  const items = [
    ...((filter === 'all' || filter === 'checkin') ? entries.map((entry) => ({ type: 'checkin' as const, id: entry.id, time: `${entry.date}T12:00:00`, entry })) : []),
    ...((filter === 'all' || filter === 'diary') ? diaryEntries.map((entry) => ({ type: 'diary' as const, id: entry.id, time: entry.createdAt, entry })) : []),
    ...((filter === 'all' || filter === 'unsent') ? urgeEntries.map((entry) => ({ type: 'unsent' as const, id: entry.id, time: entry.createdAt, entry })) : []),
  ].sort((a, b) => new Date(b.time).getTime() - new Date(a.time).getTime());

  const removeDiary = (id: string) => Alert.alert('ลบบันทึกนี้?', 'เมื่อลบแล้วจะกู้คืนไม่ได้', [{ text: 'ยกเลิก', style: 'cancel' }, { text: 'ลบ', style: 'destructive', onPress: () => { deleteDiaryEntry(id); setSelectedDiary(null); } }]);
  const removeUnsent = (id: string) => Alert.alert('ลบข้อความที่ไม่ได้ส่ง?', 'ทั้งข้อความและเสียงจะถูกลบออกจากเครื่อง', [{ text: 'ยกเลิก', style: 'cancel' }, { text: 'ลบ', style: 'destructive', onPress: () => deleteUrgeEntry(id) }]);

  return <>
    <Screen resetScrollOnFocus animateOnFocus={false}>
      <Text style={styles.title}>เรื่องราวของฉัน</Text><Text style={styles.subtitle}>ทุกวันที่ผ่านมา คือหลักฐานว่าคุณกำลังดูแลตัวเอง</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.filterScroll} contentContainerStyle={styles.filters}>
        <FilterButton label="ทั้งหมด" active={filter === 'all'} onPress={() => setFilter('all')} /><FilterButton label="เช็กอิน" active={filter === 'checkin'} onPress={() => setFilter('checkin')} /><FilterButton label="ไดอารี" active={filter === 'diary'} onPress={() => setFilter('diary')} /><FilterButton label="ไม่ได้ส่ง" active={filter === 'unsent'} onPress={() => setFilter('unsent')} />
      </ScrollView>
      {items.length ? items.map((item) => {
        if (item.type === 'checkin') return <View key={`c-${item.id}`} style={styles.entry}><Text style={styles.emoji}>{item.entry.emoji}</Text><View style={styles.body}><Text style={styles.kind}>เช็กอิน · {item.entry.mood}</Text><Text style={styles.meta}>{formatThaiDate(item.entry.date)}</Text><Text style={styles.note}>{item.entry.note}</Text></View></View>;
        if (item.type === 'diary') return <Pressable key={`d-${item.id}`} onPress={() => setSelectedDiary(item.entry)} onLongPress={() => removeDiary(item.id)} delayLongPress={350} style={styles.diaryEntry}><View style={styles.diaryCardContent}><View style={styles.diaryTop}><Text style={styles.diaryTitle}>{item.entry.emoji ? `${item.entry.emoji} ` : ''}{item.entry.title}</Text><Text style={styles.kind}>ไดอารี</Text></View><Text style={styles.meta}>{formatFullDate(item.entry.createdAt)}</Text><View style={styles.previewLines}><PaperBackground lines={4} /><Text style={styles.previewText} numberOfLines={4}>{item.entry.content}</Text></View><Text style={styles.readHint}>แตะเพื่อเปิดอ่าน</Text></View></Pressable>;
        const handleDelete = () => removeUnsent(item.id);
        return <Pressable key={`u-${item.id}`} onLongPress={handleDelete} delayLongPress={350} style={styles.chatRow}><Text style={styles.unsentLabel}>ข้อความที่ไม่ได้ส่ง</Text><View style={styles.chatBubble}><View style={styles.chatTail} />{item.entry.message ? <Text style={styles.unsentMessage}>{item.entry.message}</Text> : null}{item.entry.audioUri ? <AudioPlayback uri={item.entry.audioUri} duration={item.entry.audioDuration} onLongPress={handleDelete} /> : null}{!item.entry.message && !item.entry.audioUri ? <Text style={styles.voiceOnly}>ไม่มีข้อความ</Text> : null}</View><Text style={styles.chatTime}>{formatFullDate(item.entry.createdAt)} · กดค้างเพื่อลบ</Text></Pressable>;
      }) : <View style={styles.empty}><Text style={styles.emptyEmoji}>📖</Text><Text style={styles.emptyTitle}>เรื่องราวกำลังจะเริ่มขึ้น</Text><Text style={styles.emptyText}>บันทึกของคุณจะมาอยู่ตรงนี้</Text></View>}
    </Screen>
    <Modal visible={Boolean(selectedDiary)} animationType="slide" presentationStyle="fullScreen" onRequestClose={() => setSelectedDiary(null)}><SafeAreaView style={styles.readerSafe}><View style={styles.readerHeader}><Pressable onPress={() => setSelectedDiary(null)} style={styles.closeButton}><Text style={styles.closeText}>‹  ย้อนกลับ</Text></Pressable><Text style={styles.readerBrand}>KEEP GOING</Text><Pressable onPress={() => selectedDiary && removeDiary(selectedDiary.id)} style={styles.deleteButton}><Text style={styles.deleteText}>ลบ</Text></Pressable></View><ScrollView contentContainerStyle={styles.readerScroll} showsVerticalScrollIndicator={false}>{selectedDiary ? <View style={styles.paperReader}><View style={styles.readerContent}><Text style={styles.readerDate}>{formatFullDate(selectedDiary.createdAt)}</Text><Text style={styles.readerTitle}>{selectedDiary.emoji ? `${selectedDiary.emoji} ` : ''}{selectedDiary.title}</Text>{selectedDiary.mood ? <Text style={styles.readerMood}>ความรู้สึก · {selectedDiary.mood}</Text> : null}<View style={styles.readerLines}><PaperBackground lines={24} /><Text style={styles.readerText}>{selectedDiary.content}</Text></View></View></View> : null}</ScrollView></SafeAreaView></Modal>
  </>;
}

function AudioPlayback({ uri, duration, onLongPress }: { uri: string; duration?: number; onLongPress?: () => void }) {
  const player = useAudioPlayer(uri);
  const status = useAudioPlayerStatus(player);
  const toggle = () => { if (status.playing) return player.pause(); if (status.didJustFinish || status.currentTime >= status.duration) player.seekTo(0); player.play(); };
  const total = Math.max(1, Math.round(status.duration || duration || 0));
  return <Pressable onPress={toggle} onLongPress={onLongPress} delayLongPress={350} style={styles.audio}><View style={styles.audioPlay}><Text style={styles.audioPlayText}>{status.playing ? '❚❚' : '▶'}</Text></View><View style={styles.audioBody}><View style={styles.audioTrack}><View style={[styles.audioProgress, { width: `${Math.min(100, (status.currentTime / total) * 100)}%` }]} /></View><Text style={styles.audioTime}>{Math.floor(status.currentTime)} / {total} วินาที</Text></View></Pressable>;
}

function FilterButton({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.filter, active && styles.filterActive]}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></Pressable>; }
function formatFullDate(value: string) { return new Date(value).toLocaleString('th-TH', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }); }

const styles = StyleSheet.create({
  title: { color: colors.text, fontSize: 27, fontWeight: '800', marginTop: 18 }, subtitle: { color: colors.muted, lineHeight: 21, marginTop: 6 }, filterScroll: { flexGrow: 0, marginTop: 20, marginBottom: 22 }, filters: { height: 36, flexDirection: 'row', alignItems: 'center', gap: 8 }, filter: { height: 36, alignSelf: 'center', justifyContent: 'center', paddingHorizontal: 15, borderRadius: 18, backgroundColor: '#F1E9E9' }, filterActive: { backgroundColor: colors.primary }, filterText: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: '700' }, filterTextActive: { color: '#FFF' }, entry: { flexDirection: 'row', backgroundColor: colors.card, borderRadius: 18, padding: 16, marginBottom: 12 }, emoji: { fontSize: 28, marginRight: 12 }, body: { flex: 1 }, kind: { color: colors.primary, fontSize: 11, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 12, marginTop: 4 }, note: { color: colors.text, fontSize: 15, lineHeight: 22, marginTop: 8 },
  diaryEntry: { overflow: 'hidden', position: 'relative', backgroundColor: '#FFFDF4', borderRadius: 8, marginBottom: 12, borderWidth: 1, borderColor: '#E8E2D3', shadowColor: '#65584B', shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 }, diaryCardContent: { paddingTop: 17, paddingRight: 16, paddingBottom: 14, paddingLeft: 18 }, diaryTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, diaryTitle: { flex: 1, color: colors.text, fontSize: 17, fontWeight: '800' }, previewLines: { position: 'relative', height: 112, marginTop: 10 }, previewText: { color: colors.text, fontSize: 15, lineHeight: 28 }, readHint: { color: '#A79B96', fontSize: 10, textAlign: 'right', marginTop: 10 },
  chatRow: { alignItems: 'flex-end', marginBottom: 18, paddingRight: 5 }, unsentLabel: { color: '#AA8A93', fontSize: 10, fontWeight: '700', marginRight: 5, marginBottom: 5 }, chatBubble: { position: 'relative', minWidth: 120, maxWidth: '84%', backgroundColor: '#EECFD7', borderRadius: 21, borderBottomRightRadius: 5, paddingHorizontal: 16, paddingVertical: 12 }, chatTail: { position: 'absolute', right: -4, bottom: 0, width: 10, height: 10, backgroundColor: '#EECFD7', transform: [{ skewX: '-28deg' }] }, unsentMessage: { color: colors.text, fontSize: 16, lineHeight: 24 }, voiceOnly: { color: colors.muted, fontSize: 14, fontStyle: 'italic' }, chatTime: { color: '#AA979C', fontSize: 9, marginTop: 6, marginRight: 5 }, audio: { minWidth: 210, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.72)', borderRadius: 16, padding: 10, marginTop: 8 }, audioPlay: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, audioPlayText: { color: '#FFF', fontSize: 13, fontWeight: '800' }, audioBody: { flex: 1, marginLeft: 12 }, audioTrack: { height: 4, borderRadius: 2, backgroundColor: '#EADDE0', overflow: 'hidden' }, audioProgress: { height: 4, borderRadius: 2, backgroundColor: colors.primary }, audioTime: { color: colors.muted, fontSize: 10, marginTop: 6 },
  empty: { alignItems: 'center', backgroundColor: '#F7F0EB', borderRadius: 22, padding: 30, marginTop: 30 }, emptyEmoji: { fontSize: 42 }, emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 12 }, emptyText: { color: colors.muted, textAlign: 'center', lineHeight: 20, marginTop: 6 }, readerSafe: { flex: 1, backgroundColor: '#F3EEE5' }, readerHeader: { height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16 }, closeButton: { minWidth: 70, paddingVertical: 10 }, closeText: { color: colors.primary, fontSize: 14, fontWeight: '800' }, readerBrand: { color: '#9A8E83', fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, deleteButton: { minWidth: 70, alignItems: 'flex-end', paddingVertical: 10 }, deleteText: { color: '#B56A72', fontSize: 13, fontWeight: '700' }, readerScroll: { padding: 18, paddingBottom: 45 }, paperReader: { overflow: 'hidden', position: 'relative', minHeight: 720, backgroundColor: '#FFFDF4', borderRadius: 5, borderWidth: 1, borderColor: '#E1DACB', shadowColor: '#4B4036', shadowOpacity: 0.14, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, readerContent: { paddingTop: 28, paddingHorizontal: 24, paddingBottom: 45 }, readerDate: { color: '#9A8B82', fontSize: 12 }, readerTitle: { color: '#4E4540', fontSize: 24, lineHeight: 32, fontWeight: '800', marginTop: 14 }, readerMood: { color: colors.primary, fontSize: 12, fontWeight: '700', marginTop: 8 }, readerLines: { position: 'relative', minHeight: 672, marginTop: 24 }, readerText: { color: '#554D48', fontSize: 16, lineHeight: 28 },
});
