import { useState } from 'react';
import { Modal, Pressable, SafeAreaView, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { Screen } from '../components/Screen';
import { colors, moods } from '../constants/theme';
import { useApp } from '../context/AppContext';
import { daysSince } from '../utils/date';

const WEEKDAYS = ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'];
const moodScores: Record<string, number> = { 'หนักใจ': 1, 'เหนื่อย': 2, 'คิดถึง': 2, 'สงบ': 4, 'ดีขึ้น': 5 };

export function ProgressScreen() {
  const [chartMode, setChartMode] = useState<'week' | 'month'>('week');
  const [weekOffset, setWeekOffset] = useState(0);
  const [monthOffset, setMonthOffset] = useState(0);
  const [revealedWeeks, setRevealedWeeks] = useState<string[]>([]);
  const [summaryVisible, setSummaryVisible] = useState(false);
  const { startDate, entries, diaryEntries, urgeEntries, allowEarlyWeeklySummary } = useApp();
  const today = new Date();
  const noContactDays = daysSince(startDate);
  const activeDates = new Set([
    ...entries.map((item) => item.date),
    ...diaryEntries.map((item) => localDateKey(new Date(item.createdAt))),
    ...urgeEntries.map((item) => localDateKey(new Date(item.createdAt))),
  ]);
  const careStreak = getGentleStreak(activeDates, today);
  const growth = careStreak >= 30 ? { emoji: '🌳', label: 'ต้นไม้ของคุณแข็งแรงขึ้นมากแล้ว' } : careStreak >= 14 ? { emoji: '🌿', label: 'ใบใหม่กำลังค่อย ๆ เติบโต' } : careStreak >= 7 ? { emoji: '🪴', label: 'ความสม่ำเสมอกำลังหยั่งราก' } : careStreak >= 1 ? { emoji: '🌱', label: 'ก้าวเล็ก ๆ กำลังเริ่มเติบโต' } : { emoji: '🫘', label: 'เมล็ดพันธุ์พร้อมเริ่มใหม่จากวันนี้' };
  const weekStart = startOfWeek(today);
  weekStart.setDate(weekStart.getDate() + weekOffset * 7);
  const lastSevenDays = Array.from({ length: 7 }, (_, index) => {
    const date = new Date(weekStart);
    date.setHours(12, 0, 0, 0);
    date.setDate(date.getDate() + index);
    const key = localDateKey(date);
    return { key, label: date.toLocaleDateString('th-TH', { weekday: 'short' }).replace('.', ''), date: date.getDate(), entry: entries.find((item) => item.date === key) };
  });
  const weekEntries = lastSevenDays.flatMap((day) => day.entry ? [day.entry] : []);
  const average = weekEntries.length ? weekEntries.reduce((sum, item) => sum + (moodScores[item.mood] ?? 3), 0) / weekEntries.length : 0;
  const trend = average >= 4 ? 'ใจของคุณกำลังเบาขึ้น' : average >= 2.5 ? 'คุณกำลังค่อย ๆ ประคองตัวเอง' : weekEntries.length ? 'สัปดาห์นี้อาจหนักหน่อย พักได้เสมอนะ' : 'เริ่มเช็กอินเพื่อมองเห็นการเปลี่ยนแปลง';
  const dominantMood = getDominantMood(weekEntries.map((entry) => entry.mood));
  const profile = getWeeklyProfile(dominantMood, average, weekEntries.length);
  const weekEnd = new Date(weekStart); weekEnd.setDate(weekEnd.getDate() + 6);
  const weekStartKey = localDateKey(weekStart);
  const weekEndKey = localDateKey(weekEnd);
  const weekDiaryCount = diaryEntries.filter((entry) => { const key = localDateKey(new Date(entry.createdAt)); return key >= weekStartKey && key <= weekEndKey; }).length;
  const weekUrgeCount = urgeEntries.filter((entry) => { const key = localDateKey(new Date(entry.createdAt)); return key >= weekStartKey && key <= weekEndKey; }).length;
  const selectedWeekKey = localDateKey(weekStart);
  const officialSummaryReady = weekOffset < 0 || today.getDay() === 0;
  const summaryIsOpen = officialSummaryReady || (allowEarlyWeeklySummary && revealedWeeks.includes(selectedWeekKey));
  const weekRange = `${weekStart.toLocaleDateString('th-TH', { day: 'numeric', month: 'short' })} – ${weekEnd.toLocaleDateString('th-TH', { day: 'numeric', month: 'short' })}`;
  const calendar = buildMonth(today);
  const paddedCalendar = [...calendar, ...Array((7 - (calendar.length % 7)) % 7).fill(null)] as ({ day: number; key: string } | null)[];
  const calendarWeeks = Array.from({ length: paddedCalendar.length / 7 }, (_, index) => paddedCalendar.slice(index * 7, index * 7 + 7));
  const caredThisMonth = calendar.filter((day) => day && activeDates.has(day.key)).length;
  const selectedMonth = new Date(today.getFullYear(), today.getMonth() + monthOffset, 1, 12);
  const selectedMonthDays = buildMonthDays(selectedMonth, entries);
  const monthGroups = Array.from({ length: Math.ceil(selectedMonthDays.length / 7) }, (_, index) => {
    const days = selectedMonthDays.slice(index * 7, index * 7 + 7);
    const checkedIn = days.flatMap((day) => day.entry ? [day.entry] : []);
    const score = checkedIn.length ? checkedIn.reduce((sum, entry) => sum + (moodScores[entry.mood] ?? 3), 0) / checkedIn.length : 0;
    return { key: `month-week-${index}`, label: `สัปดาห์ ${index + 1}`, score, count: checkedIn.length, mood: getDominantMood(checkedIn.map((entry) => entry.mood)) };
  });
  const selectedMonthLabel = selectedMonth.toLocaleDateString('th-TH', { month: 'long', year: 'numeric' });
  const monthCheckIns = selectedMonthDays.filter((day) => day.entry).length;
  const shareSummary = () => Share.share({
    title: `${officialSummaryReady ? 'บทสรุปประจำสัปดาห์' : 'ภาพรวมระหว่างสัปดาห์'}จาก Keep Going`,
    message: `${officialSummaryReady ? 'บทสรุปของฉัน' : 'ภาพรวมใจของฉันในตอนนี้'} · ${weekRange}\n\n${profile.emoji} อารมณ์หลัก: ${dominantMood || 'กำลังเริ่มต้น'}\n\n${profile.title}\n\n${profile.description}\n\nสิ่งที่ใจอาจต้องการ\n${profile.care}\n\nเช็กอิน ${weekEntries.length} วัน · ไดอารี่ ${weekDiaryCount} ครั้ง · ผ่านช่วงอยากทักเขา ${weekUrgeCount} ครั้ง\n\n— Keep Going 🌱`,
  });

  return <Screen resetScrollOnFocus>
    <Text style={styles.eyebrow}>PROGRESS</Text><Text style={styles.title}>ทุกก้าวของคุณมีความหมาย</Text><Text style={styles.subtitle}>ไม่ต้องดีขึ้นทุกวัน แค่ยังเลือกดูแลตัวเองก็เพียงพอแล้ว</Text>

    <View style={styles.hero}>
      <View><Text style={styles.heroLabel}>เราไม่ได้คุยกันมา</Text><View style={styles.dayRow}><Text style={styles.dayNumber}>{noContactDays}</Text><Text style={styles.dayUnit}>วัน</Text></View></View>
      <View style={styles.heroDivider} /><View style={styles.heroSide}><Text style={styles.heroSideNumber}>{caredThisMonth}</Text><Text style={styles.heroSideLabel}>วันที่ดูแลใจตัวเอง{`\n`}ในเดือนนี้</Text></View>
    </View>

    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, styles.sectionTitleInline]}>เส้นทางอารมณ์</Text><Text style={styles.sectionHint}>{chartMode === 'week' ? `${weekEntries.length}/7 วันที่เช็กอิน` : `${monthCheckIns} วันที่เช็กอิน`}</Text></View>
    <View style={styles.chartTabs}>
      <Pressable onPress={() => setChartMode('week')} style={[styles.chartTab, chartMode === 'week' && styles.chartTabActive]}><Text style={[styles.chartTabText, chartMode === 'week' && styles.chartTabTextActive]}>สัปดาห์</Text></Pressable>
      <Pressable onPress={() => setChartMode('month')} style={[styles.chartTab, chartMode === 'month' && styles.chartTabActive]}><Text style={[styles.chartTabText, chartMode === 'month' && styles.chartTabTextActive]}>เดือน</Text></Pressable>
    </View>
    <View style={styles.weekCard}>
      {chartMode === 'week' ? <View style={styles.weeklyCounts}><MiniCount value={weekEntries.length} label="เช็กอิน" /><MiniCount value={weekDiaryCount} label="ไดอารี่" /><MiniCount value={weekUrgeCount} label="ผ่านช่วงคิดถึง" /></View> : null}
      {chartMode === 'week' ? <>
        <View style={styles.weekNav}><Pressable onPress={() => setWeekOffset((value) => value - 1)} style={styles.weekArrow} hitSlop={8}><Text style={styles.weekArrowText}>‹</Text></Pressable><Pressable onPress={() => setWeekOffset(0)} disabled={weekOffset === 0} style={styles.weekRangeButton}><Text style={styles.weekRange}>{weekOffset === 0 ? 'สัปดาห์นี้' : weekRange}</Text>{weekOffset !== 0 ? <Text style={styles.backToCurrent}>แตะเพื่อกลับสัปดาห์นี้</Text> : <Text style={styles.weekDates}>{weekRange}</Text>}</Pressable><Pressable onPress={() => setWeekOffset((value) => Math.min(0, value + 1))} disabled={weekOffset === 0} style={[styles.weekArrow, weekOffset === 0 && styles.weekArrowDisabled]} hitSlop={8}><Text style={styles.weekArrowText}>›</Text></Pressable></View>
        <View style={styles.chart}>{lastSevenDays.map((day) => { const mood = moods.find((item) => item.label === day.entry?.mood); const score = day.entry ? (moodScores[day.entry.mood] ?? 3) : 0; return <View key={day.key} style={styles.chartDay}><View style={styles.barTrack}>{score ? <View style={[styles.bar, { height: 14 + score * 12, backgroundColor: mood?.color ?? colors.primary }]} /> : <View style={styles.emptyDot} />}</View><Text style={styles.chartEmoji}>{day.entry?.emoji ?? '·'}</Text><Text style={styles.chartLabel}>{day.label}</Text><Text style={styles.chartDate}>{day.date}</Text></View>; })}</View>
        {summaryIsOpen ? <Pressable onPress={() => setSummaryVisible(true)} style={styles.trend}><Text style={styles.trendIcon}>♡</Text><View style={styles.trendBody}><Text style={styles.trendLabel}>{officialSummaryReady ? 'สรุปสัปดาห์นี้พร้อมแล้ว' : 'ภาพรวมระหว่างสัปดาห์'}</Text><Text style={styles.trendText}>{officialSummaryReady ? trend : `${trend} · ข้อมูลอาจเปลี่ยนได้จนถึงวันอาทิตย์`} · แตะเพื่อเปิดอ่าน</Text></View><Text style={styles.revealArrow}>›</Text></Pressable> : <Pressable disabled={!allowEarlyWeeklySummary} onPress={() => { setRevealedWeeks((weeks) => [...weeks, selectedWeekKey]); setSummaryVisible(true); }} style={[styles.lockedSummary, !allowEarlyWeeklySummary && styles.lockedSummaryWaiting]}><View style={styles.lockedIcon}><Text style={styles.lockedIconText}>♡</Text></View><View style={styles.trendBody}><Text style={styles.lockedTitle}>สรุปยังไม่พร้อมในวันนี้</Text><Text style={styles.lockedText}>{allowEarlyWeeklySummary ? 'สรุปเต็มจะพร้อมวันอาทิตย์ หรือแตะเพื่อเปิดภาพรวมก่อนได้' : 'ใจของคุณกำลังค่อย ๆ เก็บเรื่องราว แล้วกลับมาเปิดพร้อมกันในวันอาทิตย์นะ'}</Text></View>{allowEarlyWeeklySummary ? <Text style={styles.revealArrow}>›</Text> : null}</Pressable>}
      </> : <>
        <View style={styles.weekNav}><Pressable onPress={() => setMonthOffset((value) => value - 1)} style={styles.weekArrow} hitSlop={8}><Text style={styles.weekArrowText}>‹</Text></Pressable><Pressable onPress={() => setMonthOffset(0)} disabled={monthOffset === 0} style={styles.weekRangeButton}><Text style={styles.weekRange}>{monthOffset === 0 ? 'เดือนนี้' : selectedMonthLabel}</Text><Text style={styles.weekDates}>{selectedMonthLabel}</Text></Pressable><Pressable onPress={() => setMonthOffset((value) => Math.min(0, value + 1))} disabled={monthOffset === 0} style={[styles.weekArrow, monthOffset === 0 && styles.weekArrowDisabled]} hitSlop={8}><Text style={styles.weekArrowText}>›</Text></Pressable></View>
        <View style={styles.monthChart}>{monthGroups.map((group) => { const mood = moods.find((item) => item.label === group.mood); return <View key={group.key} style={styles.monthColumn}><View style={styles.monthBarTrack}>{group.score ? <View style={[styles.monthBar, { height: 18 + group.score * 14, backgroundColor: mood?.color ?? colors.primary }]} /> : <View style={styles.emptyDot} />}</View><Text style={styles.monthEmoji}>{mood?.emoji ?? '·'}</Text><Text style={styles.monthLabel}>{group.label}</Text><Text style={styles.monthCount}>{group.count} วัน</Text></View>; })}</View>
        <Text style={styles.monthNote}>{monthCheckIns ? `เดือนนี้คุณกลับมารับฟังใจตัวเอง ${monthCheckIns} วัน` : 'เดือนนี้ยังไม่มีข้อมูล เริ่มจากเช็กอินวันแรกได้เสมอ'}</Text>
      </>}
    </View>

    <Text style={styles.sectionTitle}>ภาพรวมของฉัน</Text>
    <View style={styles.stats}><Stat value={entries.length} label="เช็กอิน" emoji="☀️" /><Stat value={diaryEntries.length} label="ไดอารี่" emoji="✍️" /><Stat value={urgeEntries.length} label="ผ่านช่วงคิดถึง" emoji="🌱" /></View>
    <View style={styles.growthCard}><Text style={styles.growthEmoji}>{growth.emoji}</Text><View style={styles.growthBody}><Text style={styles.growthEyebrow}>ช่วงที่กลับมาดูแลตัวเอง</Text><Text style={styles.growthTitle}>{careStreak ? `${careStreak} วันต่อเนื่อง` : 'เริ่มต่อจากวันนี้ได้เสมอ'}</Text><Text style={styles.growthText}>{growth.label} ไม่ต้องชดเชยวันที่หายไป แค่กลับมาเมื่อพร้อมก็พอ</Text></View></View>

    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, styles.sectionTitleInline]}>{today.toLocaleDateString('th-TH', { month: 'long', year: 'numeric' })}</Text><Text style={styles.sectionHint}>วันที่มีสีคือวันที่คุณดูแลใจ</Text></View>
    <View style={styles.calendarCard}>
      <View style={styles.calendarRow}>{WEEKDAYS.map((day) => <Text key={day} style={styles.weekday}>{day}</Text>)}</View>
      <View style={styles.calendarGrid}>{calendarWeeks.map((week, weekIndex) => <View key={`week-${weekIndex}`} style={styles.calendarRow}>{week.map((day, dayIndex) => <View key={day?.key ?? `empty-${weekIndex}-${dayIndex}`} style={styles.calendarCell}>{day ? <View style={[styles.dateCircle, activeDates.has(day.key) && styles.activeDate, day.key === localDateKey(today) && styles.today]}><Text style={[styles.dateText, activeDates.has(day.key) && styles.activeDateText]}>{day.day}</Text></View> : null}</View>)}</View>)}</View>
      <View style={styles.legend}><View style={styles.legendDot} /><Text style={styles.legendText}>คุณกลับมาดูแลใจตัวเองในวันนี้</Text></View>
    </View>
    <Modal visible={summaryVisible} animationType="slide" presentationStyle="fullScreen" onRequestClose={() => setSummaryVisible(false)}><SafeAreaView style={styles.summarySafe}><View style={styles.summaryHeader}><Pressable onPress={() => setSummaryVisible(false)} style={styles.summaryBack}><Text style={styles.summaryBackText}>‹  ย้อนกลับ</Text></Pressable><Text style={styles.summaryBrand}>KEEP GOING</Text><View style={styles.summaryHeaderSpace} /></View><ScrollView contentContainerStyle={styles.summaryScroll} showsVerticalScrollIndicator={false}><Text style={styles.summaryOverline}>{officialSummaryReady ? 'เรื่องราวของใจ' : 'ภาพรวมระหว่างสัปดาห์'} · {weekRange}</Text><Text style={styles.summaryTitle}>สัปดาห์นี้{`\n`}ใจของคุณเป็นแบบไหน</Text>{!officialSummaryReady ? <Text style={styles.earlyNotice}>นี่คือภาพรวมจากข้อมูลในตอนนี้ และอาจเปลี่ยนแปลงได้จนถึงวันอาทิตย์</Text> : null}<View style={styles.summaryMood}><Text style={styles.summaryEmoji}>{profile.emoji}</Text><Text style={styles.summaryMoodLabel}>อารมณ์ที่อยู่กับคุณบ่อยที่สุด</Text><Text style={styles.summaryMoodName}>{dominantMood || 'กำลังเริ่มต้น'}</Text></View><View style={styles.readingCard}><Text style={styles.readingLead}>{profile.title}</Text><Text style={styles.readingText}>{profile.description}</Text><View style={styles.readingDivider} /><Text style={styles.readingLabel}>สิ่งที่ใจคุณอาจต้องการ</Text><Text style={styles.readingText}>{profile.care}</Text></View><View style={styles.weekFacts}><View style={styles.fact}><Text style={styles.factValue}>{weekEntries.length}</Text><Text style={styles.factLabel}>วันที่รับฟังใจ</Text></View><View style={styles.factDivider} /><View style={styles.fact}><Text style={styles.factValue}>{dominantMood ? moods.find((mood) => mood.label === dominantMood)?.emoji ?? '♡' : '♡'}</Text><Text style={styles.factLabel}>อารมณ์หลัก</Text></View></View><Text style={styles.summaryClosing}>คุณไม่จำเป็นต้องรู้สึกดีตลอดเวลา{`\n`}แค่ซื่อสัตย์กับความรู้สึกของตัวเอง ก็เก่งมากแล้ว</Text><Pressable onPress={shareSummary} style={styles.shareButton}><Text style={styles.shareIcon}>↗</Text><Text style={styles.shareText}>{officialSummaryReady ? 'แชร์บทสรุป' : 'แชร์ภาพรวมตอนนี้'}</Text></Pressable><Text style={styles.shareHint}>แชร์เฉพาะข้อความนี้ ไม่รวมบันทึกส่วนตัวของคุณ</Text><Pressable onPress={() => setSummaryVisible(false)} style={styles.doneButton}><Text style={styles.doneText}>เก็บไว้ในใจ</Text></Pressable></ScrollView></SafeAreaView></Modal>
  </Screen>;
}

function Stat({ value, label, emoji }: { value: number; label: string; emoji: string }) { return <View style={styles.stat}><Text style={styles.statEmoji}>{emoji}</Text><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function MiniCount({ value, label }: { value: number; label: string }) { return <View style={styles.miniCount}><Text style={styles.miniCountValue}>{value}</Text><Text style={styles.miniCountLabel}>{label}</Text></View>; }
function localDateKey(date: Date) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, '0'); const day = String(date.getDate()).padStart(2, '0'); return `${year}-${month}-${day}`; }
function startOfWeek(date: Date) { const result = new Date(date); result.setHours(12, 0, 0, 0); const day = result.getDay(); result.setDate(result.getDate() - (day === 0 ? 6 : day - 1)); return result; }
function buildMonthDays(date: Date, entries: { date: string; mood: string; emoji: string }[]) { const year = date.getFullYear(); const month = date.getMonth(); const count = new Date(year, month + 1, 0).getDate(); return Array.from({ length: count }, (_, index) => { const value = new Date(year, month, index + 1, 12); const key = localDateKey(value); return { key, day: index + 1, entry: entries.find((item) => item.date === key) }; }); }
function getGentleStreak(activeDates: Set<string>, today: Date) { const cursor = new Date(today); cursor.setHours(12, 0, 0, 0); if (!activeDates.has(localDateKey(cursor))) cursor.setDate(cursor.getDate() - 1); let count = 0; while (activeDates.has(localDateKey(cursor))) { count += 1; cursor.setDate(cursor.getDate() - 1); } return count; }
function getDominantMood(values: string[]) { if (!values.length) return ''; const counts = values.reduce<Record<string, number>>((result, mood) => ({ ...result, [mood]: (result[mood] ?? 0) + 1 }), {}); return Object.entries(counts).sort((a, b) => b[1] - a[1])[0][0]; }
function getWeeklyProfile(mood: string, average: number, count: number) {
  if (!count) return { emoji: '🌱', title: 'ใจของคุณกำลังรอให้คุณกลับมารับฟัง', description: 'สัปดาห์นี้ยังไม่มีคำตอบจากการเช็กอิน ไม่เป็นไรเลย บางครั้งการเงียบก็เป็นวิธีพักของหัวใจได้เหมือนกัน', care: 'ลองถามตัวเองสั้น ๆ ว่า “วันนี้ฉันต้องการอะไร” แล้วตอบเพียงคำเดียวก็พอ' };
  if (mood === 'คิดถึง') return { emoji: '🌧️', title: 'คุณเป็นคนที่ยังรู้สึกผูกพัน แต่กำลังพยายามเลือกตัวเอง', description: 'ความคิดถึงแวะมาหาคุณบ่อยในสัปดาห์นี้ มันไม่ได้หมายความว่าคุณถอยหลัง เพียงแค่หัวใจยังจดจำสิ่งที่เคยสำคัญ ขณะเดียวกันคุณก็ยังกลับมาเช็กอินและรับฟังตัวเองอยู่เสมอ', care: 'ให้พื้นที่กับความคิดถึงโดยไม่ต้องทำตามมัน เขียนสิ่งที่อยากพูด หายใจช้า ๆ แล้วรอให้คลื่นความรู้สึกค่อย ๆ ผ่านไป' };
  if (mood === 'หนักใจ' || average < 2) return { emoji: '🫧', title: 'คุณกำลังแบกหลายความรู้สึก แต่ยังไม่ยอมทิ้งตัวเอง', description: 'สัปดาห์นี้อาจใช้พลังจากคุณมากกว่าปกติ การที่คุณยังกลับมาบอกความรู้สึกของตัวเอง แปลว่าลึก ๆ แล้วคุณยังพยายามดูแลหัวใจดวงนี้อยู่', care: 'ลดสิ่งที่ต้องทำลงหนึ่งอย่าง พักโดยไม่รู้สึกผิด และขอความช่วยเหลือจากคนที่ไว้ใจได้เมื่อความรู้สึกหนักเกินรับไหว' };
  if (mood === 'เหนื่อย') return { emoji: '🌙', title: 'คุณพยายามมานาน และหัวใจกำลังขอเวลาพัก', description: 'ความเหนื่อยไม่ได้แปลว่าคุณอ่อนแอ แต่มันบอกว่าคุณใช้พลังไปมากแล้ว สัปดาห์นี้คุณอาจไม่ต้องเร่งให้ตัวเองมูฟออน แค่ประคองวันธรรมดาให้ผ่านไปก็เพียงพอ', care: 'พักหน้าจอเร็วขึ้น ดื่มน้ำ และเลือกทำสิ่งเล็กที่สุดที่ทำให้ร่างกายรู้สึกปลอดภัย' };
  if (mood === 'สงบ') return { emoji: '🍃', title: 'คุณกำลังกลับมาอยู่กับตัวเองได้มากขึ้น', description: 'ความสงบเริ่มมีพื้นที่ในสัปดาห์นี้ นั่นไม่ได้แปลว่าความคิดถึงจะไม่กลับมา แต่แปลว่าคุณเริ่มรู้แล้วว่าจะอยู่กับมันอย่างไรโดยไม่ทำร้ายตัวเอง', care: 'รักษาจังหวะที่สบายนี้ไว้ ไม่ต้องเร่งไปข้างหน้า และบันทึกสิ่งเล็ก ๆ ที่ทำให้คุณรู้สึกสงบ' };
  return { emoji: '☀️', title: 'ใจของคุณกำลังเบาขึ้น และคุณเริ่มเห็นตัวเองชัดขึ้น', description: 'สัปดาห์นี้มีช่วงเวลาที่ดีขึ้นมากกว่าเดิม สิ่งนี้เกิดจากก้าวเล็ก ๆ ที่คุณเลือกทำเพื่อตัวเอง ไม่ใช่เพราะคุณลืมใครได้ทันที แต่เพราะคุณเริ่มกลับมาให้ความสำคัญกับชีวิตของคุณ', care: 'อนุญาตให้ตัวเองมีความสุขโดยไม่ต้องรู้สึกผิด และเก็บช่วงเวลาที่ดีนี้ไว้เป็นหลักฐานว่าคุณไปต่อได้' };
}
function buildMonth(date: Date) { const year = date.getFullYear(); const month = date.getMonth(); const firstDay = new Date(year, month, 1).getDay(); const days = new Date(year, month + 1, 0).getDate(); return [...Array(firstDay).fill(null), ...Array.from({ length: days }, (_, index) => { const value = new Date(year, month, index + 1); return { day: index + 1, key: localDateKey(value) }; })] as ({ day: number; key: string } | null)[]; }

const styles = StyleSheet.create({
  lockedSummaryWaiting: { backgroundColor: '#F3EFF0' },
  earlyNotice: { color: '#8F7981', fontSize: 11, lineHeight: 17, backgroundColor: '#F5E8EC', borderRadius: 12, paddingHorizontal: 13, paddingVertical: 10, marginTop: 14 },
  eyebrow: { color: colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1.8, marginTop: 14 }, title: { color: colors.text, fontSize: 28, lineHeight: 36, fontWeight: '800', marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 22, marginTop: 7 },
  hero: { minHeight: 140, borderRadius: 24, backgroundColor: colors.primarySoft, padding: 20, marginTop: 24, flexDirection: 'row', alignItems: 'center' }, heroLabel: { color: '#816D75', fontSize: 13 }, dayRow: { flexDirection: 'row', alignItems: 'baseline', marginTop: 5 }, dayNumber: { color: colors.primary, fontSize: 50, lineHeight: 58, fontWeight: '800' }, dayUnit: { color: colors.primary, fontSize: 15, fontWeight: '800', marginLeft: 7 }, heroDivider: { width: 1, height: 72, backgroundColor: '#DFC9CF', marginHorizontal: 20 }, heroSide: { flex: 1, alignItems: 'center' }, heroSideNumber: { color: colors.text, fontSize: 29, fontWeight: '800' }, heroSideLabel: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 5 },
  sectionHeader: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 28, marginBottom: 12 }, sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 28 }, sectionTitleInline: { marginTop: 0 }, sectionHint: { color: colors.muted, fontSize: 10, marginBottom: 2 }, weekCard: { backgroundColor: '#FFF', borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 16 }, weekNav: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#F1E7E9', marginBottom: 10, paddingBottom: 10 }, weekArrow: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7EEF0' }, weekArrowDisabled: { opacity: 0.3 }, weekArrowText: { color: colors.primary, fontSize: 28, lineHeight: 30, fontWeight: '600' }, weekRangeButton: { flex: 1, alignItems: 'center', justifyContent: 'center' }, weekRange: { color: colors.text, fontSize: 13, fontWeight: '800' }, weekDates: { color: colors.muted, fontSize: 10, marginTop: 3 }, backToCurrent: { color: colors.primary, fontSize: 9, marginTop: 3 }, chart: { height: 136, flexDirection: 'row', justifyContent: 'space-between' }, chartDay: { flex: 1, alignItems: 'center' }, barTrack: { height: 76, justifyContent: 'flex-end', alignItems: 'center' }, bar: { width: 12, maxHeight: 74, borderRadius: 6 }, emptyDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#DDD2D5' }, chartEmoji: { fontSize: 14, height: 20, marginTop: 4 }, chartLabel: { color: colors.muted, fontSize: 10 }, chartDate: { color: '#B0A4A8', fontSize: 9, marginTop: 2 }, trend: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF7F5', borderRadius: 14, padding: 12, marginTop: 4 }, trendBody: { flex: 1 }, trendIcon: { color: colors.primary, fontSize: 19, marginRight: 9 }, trendLabel: { color: colors.primary, fontSize: 10, fontWeight: '800', marginBottom: 3 }, trendText: { color: '#755F68', fontSize: 12, lineHeight: 18 }, lockedSummary: { minHeight: 72, flexDirection: 'row', alignItems: 'center', backgroundColor: '#F7F1F2', borderRadius: 14, padding: 12, marginTop: 4 }, lockedIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#EADDE0', alignItems: 'center', justifyContent: 'center', marginRight: 10 }, lockedIconText: { color: '#A98C94', fontSize: 18 }, lockedTitle: { color: colors.text, fontSize: 11, fontWeight: '800' }, lockedText: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }, revealArrow: { color: colors.primary, fontSize: 25, marginLeft: 5 },
  chartTabs: { flexDirection: 'row', backgroundColor: '#EFE8E9', borderRadius: 13, padding: 3, marginBottom: 10 }, chartTab: { flex: 1, minHeight: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, chartTabActive: { backgroundColor: '#FFFFFF', shadowColor: '#6B5960', shadowOpacity: 0.08, shadowRadius: 5, shadowOffset: { width: 0, height: 2 } }, chartTabText: { color: colors.muted, fontSize: 12, fontWeight: '700' }, chartTabTextActive: { color: colors.primary, fontWeight: '800' }, monthChart: { height: 150, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', paddingHorizontal: 4 }, monthColumn: { flex: 1, alignItems: 'center' }, monthBarTrack: { height: 88, justifyContent: 'flex-end', alignItems: 'center' }, monthBar: { width: 22, maxHeight: 88, borderRadius: 11 }, monthEmoji: { height: 21, fontSize: 14, marginTop: 4 }, monthLabel: { color: colors.muted, fontSize: 9, fontWeight: '700' }, monthCount: { color: '#B0A4A8', fontSize: 8, marginTop: 2 }, monthNote: { color: '#755F68', fontSize: 11, lineHeight: 17, textAlign: 'center', backgroundColor: '#FFF7F5', borderRadius: 13, padding: 11, marginTop: 8 },
  weeklyCounts: { flexDirection: 'row', backgroundColor: '#FFF8F5', borderRadius: 14, marginBottom: 12, paddingVertical: 10 }, miniCount: { flex: 1, alignItems: 'center' }, miniCountValue: { color: colors.text, fontSize: 16, fontWeight: '800' }, miniCountLabel: { color: colors.muted, fontSize: 8, marginTop: 2 },
  stats: { flexDirection: 'row', gap: 9, marginTop: 12 }, stat: { flex: 1, minHeight: 112, backgroundColor: '#FFF', borderRadius: 18, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', padding: 8 }, statEmoji: { fontSize: 20 }, statValue: { color: colors.text, fontSize: 24, fontWeight: '800', marginTop: 5 }, statLabel: { color: colors.muted, fontSize: 10, textAlign: 'center', marginTop: 2 },
  growthCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F0F3EA', borderRadius: 22, padding: 18, marginTop: 12 }, growthEmoji: { fontSize: 43, marginRight: 15 }, growthBody: { flex: 1 }, growthEyebrow: { color: '#718069', fontSize: 9, fontWeight: '800', letterSpacing: 0.5 }, growthTitle: { color: '#4F5B4B', fontSize: 17, fontWeight: '800', marginTop: 4 }, growthText: { color: '#74806F', fontSize: 11, lineHeight: 17, marginTop: 5 },
  calendarCard: { backgroundColor: '#FFF', borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 15 }, calendarRow: { flexDirection: 'row', width: '100%' }, weekday: { flex: 1, color: '#9D9095', fontSize: 10, fontWeight: '700', textAlign: 'center', paddingBottom: 10 }, calendarGrid: { width: '100%' }, calendarCell: { flex: 1, height: 39, alignItems: 'center', justifyContent: 'center' }, dateCircle: { width: 31, height: 31, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, activeDate: { backgroundColor: '#EBCFD6' }, today: { borderWidth: 1.5, borderColor: colors.primary }, dateText: { color: colors.muted, fontSize: 12 }, activeDateText: { color: colors.text, fontWeight: '800' }, legend: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 12 }, legendDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#EBCFD6', marginRight: 6 }, legendText: { color: colors.muted, fontSize: 10 },
  summarySafe: { flex: 1, backgroundColor: '#FFF9F5' }, summaryHeader: { height: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18 }, summaryBack: { width: 86, paddingVertical: 10 }, summaryBackText: { color: colors.primary, fontSize: 14, fontWeight: '800' }, summaryBrand: { color: '#A18F94', fontSize: 10, fontWeight: '800', letterSpacing: 1.5 }, summaryHeaderSpace: { width: 86 }, summaryScroll: { paddingHorizontal: 25, paddingTop: 34, paddingBottom: 48 }, summaryOverline: { color: colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 0.5 }, summaryTitle: { color: colors.text, fontSize: 31, lineHeight: 41, fontWeight: '800', marginTop: 12 }, summaryMood: { alignItems: 'center', backgroundColor: '#F5E8EC', borderRadius: 26, padding: 24, marginTop: 26 }, summaryEmoji: { fontSize: 46 }, summaryMoodLabel: { color: colors.muted, fontSize: 11, marginTop: 10 }, summaryMoodName: { color: colors.text, fontSize: 22, fontWeight: '800', marginTop: 4 }, readingCard: { backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 21, marginTop: 16 }, readingLead: { color: colors.text, fontSize: 19, lineHeight: 28, fontWeight: '800' }, readingText: { color: '#756970', fontSize: 15, lineHeight: 25, marginTop: 12 }, readingDivider: { height: 1, backgroundColor: '#F0E5E7', marginVertical: 19 }, readingLabel: { color: colors.primary, fontSize: 11, fontWeight: '800' }, weekFacts: { minHeight: 92, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF4EE', borderRadius: 20, marginTop: 16 }, fact: { flex: 1, alignItems: 'center' }, factValue: { color: colors.text, fontSize: 24, fontWeight: '800' }, factLabel: { color: colors.muted, fontSize: 10, marginTop: 3 }, factDivider: { width: 1, height: 48, backgroundColor: '#E9DCD5' }, summaryClosing: { color: '#796C73', fontSize: 15, lineHeight: 25, textAlign: 'center', marginTop: 28 }, shareButton: { minHeight: 52, borderRadius: 17, borderWidth: 1.5, borderColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 24 }, shareIcon: { color: colors.primary, fontSize: 19, fontWeight: '800', marginRight: 8 }, shareText: { color: colors.primary, fontSize: 14, fontWeight: '800' }, shareHint: { color: colors.muted, fontSize: 9, textAlign: 'center', marginTop: 7 }, doneButton: { minHeight: 54, borderRadius: 17, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginTop: 14 }, doneText: { color: '#FFF', fontSize: 14, fontWeight: '800' },
});
